In [1]:
import numpy as np
a = np.array([1, 2, 3, 7, 8, 24])
b = np.zeros((5, 6))
c = np.ones((5, 5))
d = np.arange(2, 8)
print(a, '\n', b, '\n', c, '\n', d)

[ 1  2  3  7  8 24] 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 [2 3 4 5 6 7]


In [2]:
print(a.shape, a.dtype, type(a), '\n',
     b.shape, b.dtype, type(b), '\n',
     c.shape, c.dtype, type(c), '\n',
     d.shape, d.dtype, type(d), '\n',)

(6,) int64 <class 'numpy.ndarray'> 
 (5, 6) float64 <class 'numpy.ndarray'> 
 (5, 5) float64 <class 'numpy.ndarray'> 
 (6,) int64 <class 'numpy.ndarray'> 



In [3]:
print(a[1], a[[0, 2]], a[0:2],'\n', b[0][1], b[[1, 3], [3, 3]],'\n', b[2:5, 2:5])

2 [1 3] [1 2] 
 0.0 [0. 0.] 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
z = a*d
print(z)
x = np.mean(z)/(z.max()+z.min())
print(x)

[  2   6  12  35  48 168]
0.2656862745098039
